---
- name: configure prometheus
  tags:
    - config
  template:
    src: "../templates/etc/prometheus/prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
    validate: "{{ prometheus_bin_dir }}/promtool check-config %s"
  notify:
    - reload prometheus

