---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: reload prometheus
  service:
    name: prometheus
    state: reloaded
